services:
  php:
    build: .
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ecommerce
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.4.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  rabbitmq:
    image: rabbitmq
  neo4j:
    image: neo4j
    environment:
      NEO4J_AUTH: neo4j/12345678
    ports:
      - 7474:7474
      - 7687:7687
